### ISSUE TITLE
Help does not correspond to code

### ISSUE THREAD

**Issue by robinro** [glensc/moin2doku#3]
the option -F no longer works and -f has a different meaning

**Comment by glensc** [comment]
I'm sorry, i'm not interested fixing this. I got my conversion done :)

Altho, I do accept patches (pull requests) to sane amount.

I put repo online so others have better starting point than I did.

**Comment by robinro** [comment]
Maybe I'll spend some time in updating the code. Depending on how quickly my conversion moves along. Thanks for your work and sharing the code.
